# pyproject.toml

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "retrievers"
version = "0.0.1"

dependencies = [
    "torch",
    "transformers",
    'numpy',
]

[project.optional-dependencies]
dev = ["pip-tools", "pytest"]
